#### Task 3: Import NumPy

This one is easy - just import the package 😄. Make sure to follow the conventions, though!

In [1]:
import numpy as np

#### Task 4: Python vs NumPy

Use pure Python and `numpy` to create a Python list/`numpy`:

- array of $10$ zeros;
- array of $10$ ones;
- array of $10$ fives;
- array of $10$ zeroes, the fifth value of which is $1$;
- array of all the integers from $10$ to $50$;
- array of all the even integers from $10$ to $50$;
- array that is the reversal of the list `[1, 2, 3]` (save these values in an object and use both methods to reverse that object);
- a 3x3 matrix with values ranging from $0$ to $8$;
- a 3x3 identity matrix;
- a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [2]:
zeros = [0] * 10
np_zeros = np.zeros(10)

ones = [1] * 10
np_ones = np.ones(10)

fives = [5] * 10
np_fives = np.full(10, 5)

zeros_and_five = zeros.copy()
zeros_and_five.insert(5, 5)
np_zeros_and_five = np.zeros(11)
np_zeros_and_five[5] = 5

ten_to_fifty = list(range(10, 51))
np_ten_to_fifty = np.arange(10, 51)

ten_to_fifty_even = list(range(10, 51, 2))
np_ten_to_fifty_even = np.arange(10, 51, 2)

one_to_three = [1,2,3]
one_to_three_rev = one_to_three[::-1]
np_one_to_three_rev = np.flip(one_to_three)

zero_to_eight_matrix = [[0, 1, 2],[3, 4, 5],[6, 7, 8]]
np_zero_to_eight_matrix = np.arange(0, 9).reshape(3, 3)

identity = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
np_identity = np.identity(3)

one_to_four_diagonal = [[0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 2, 0, 0, 0],
                        [0, 0, 3, 0, 0], [0, 0, 0, 4, 0]]
np_one_to_four_diagonal = np.diag(np.arange(1, 5), k=-1)

In [3]:
print('array of 10 zeros')
print(f'Python: {zeros}')
print(f'Numpy: {np_zeros}\n')

print('array of 10 ones')
print(f'Python: {ones}')
print(f'Numpy: {np_ones}\n')

print('array of 10 fives')
print(f'Python: {fives}')
print(f'Numpy: {np_fives}\n')

print('array of 10 zeros, the fifth value of which is 1')
print(f'Python: {zeros_and_five}')
print(f'Numpy: {np_zeros_and_five}\n')

print('array of all integers from 10 to 50')
print(f'Python: {ten_to_fifty}')
print(f'Numpy: {np_ten_to_fifty}\n')

print('array of all even integers from 10 to 50')
print(f'Python: {ten_to_fifty_even}')
print(f'Numpy: {np_ten_to_fifty_even}\n')

print('[1,2,3] reversed')
print(f'Python: {one_to_three_rev}')
print(f'Numpy: {np_one_to_three_rev}\n')

print('0 to 8 matrix')
print(f'Python: {zero_to_eight_matrix}')
print(f'Numpy: \n{np_zero_to_eight_matrix}\n')

print('3*3 identity matrix')
print(f'Python: {identity}')
print(f'Numpy: \n{np_identity}\n')

print('5*5 with 1 to 4 under the diagonal')
print(f'Python: {one_to_four_diagonal}')
print(f'Numpy: \n{np_one_to_four_diagonal}\n')



array of 10 zeros
Python: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

array of 10 ones
Python: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Numpy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

array of 10 fives
Python: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Numpy: [5 5 5 5 5 5 5 5 5 5]

array of 10 zeros, the fifth value of which is 1
Python: [0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]

array of all integers from 10 to 50
Python: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Numpy: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

array of all even integers from 10 to 50
Python: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
Numpy: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

[1,2,3] reversed
Python: [3, 2, 1]
N

#### Task 5: Using only NumPy:

1. Create a 5x5 array with $1$ on the border and $0$ inside.
2. Add a border filled with $0$'s on the two sides of an array `[1, 2, 3]`.
3. Create an array of $20$ equally spaced numbers between $0$ and $1$.
4. Create the following matrix:

```text
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

5. Find the indices of the non-zero elements in `[1, 2, 0, 0, 4, 0]`.

In [4]:
five_by_five_ones_around = np.ones((5, 5)) - np.pad(np.ones((3, 3)), 1)
one_to_three_zero_border = np.pad(np.arange(1, 4, 1), 1)
zero_to_one_twenty = np.linspace(0, 1, 20)
zero_to_one_matrix = np.reshape(np.linspace(0.01, 1, 100), (10, 10))
array_with_some_zeroes = np.array([1, 2, 0, 0, 4, 0])

In [5]:
print('5*5 array with ones on the border and zeros inside:')
print(five_by_five_ones_around)

print('\n[1,2,3] with on the sides')
print(one_to_three_zero_border)

print('\n20 evenly spaced numbers from 0 to 1')
print(zero_to_one_twenty)

print('\n0.01 to 1 spaced by 0.01 matrix')
print(zero_to_one_matrix)

print('\nindices of the non-zero elements in [1, 2, 0, 0, 4, 0]')
print(np.argwhere(array_with_some_zeroes != 0).flatten())


5*5 array with ones on the border and zeros inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[1,2,3] with on the sides
[0 1 2 3 0]

20 evenly spaced numbers from 0 to 1
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

0.01 to 1 spaced by 0.01 matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.9

#### Task 6: Use NumPy to generate:

- a random number between 0 and 1;
- an array of 25 random numbers sampled from a standard normal distribution;
- a 3x3x3 array with random values drawn from the uniform distribution;
- a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values;
- a random array with values drawn from the uniform distribution of size 30 and find the mean value;
- and multiply a 5x3 matrix by a 3x2 matrix.

**Note**: Your values should be different from the one shown below due to randomness.

In [6]:
rnd = np.random.rand(0, 1)
random_25 = np.random.randn(25)
random_3_cube = np.random.rand(3, 3, 3)
random_10_by_10 = np.random.rand(10, 10)
random_30 = np.random.rand(30)
random_5_by_3 = np.random.rand(5, 3)
random_3_by_2 = np.random.rand(3, 2)

In [7]:
print('a random number between 0 and 1')
print(rnd)

print(
    '\nan array of 25 random numbers sampled from a standard normal distribution'
)
print(random_25)

print('\na 3x3x3 array with random uniform distribution values')
print(random_3_cube)

print('\n10x10 array of random values from the uniform distribution')
print(random_10_by_10)
print(f'Min: {np.min(random_10_by_10)} ; Max: {np.max(random_10_by_10)}')

print('\narray of 30 random values from the uniform distribution')
print(random_30)
print(f'Mean: {np.mean(random_30)}')

print('\n5x3 matrix multiplied by 3x2 matrix with random values')
print(np.dot(random_5_by_3, random_3_by_2))

a random number between 0 and 1
[]

an array of 25 random numbers sampled from a standard normal distribution
[-0.50116775  1.5215593  -0.80976688  2.09169822 -0.71197455  0.98478494
  1.87815245 -1.06027198  1.21614483 -1.1416019  -1.58054582  1.07553389
 -1.23000979 -0.29434119 -1.14744511  2.22555851  0.11865158  0.02024052
 -1.37490717 -1.71791548 -0.60650213  0.57737355  0.88408605 -0.67347556
 -0.78813311]

a 3x3x3 array with random uniform distribution values
[[[5.88379478e-01 4.49519546e-02 5.14935515e-01]
  [8.45693055e-01 6.59210031e-04 8.10845292e-01]
  [8.93920897e-01 7.76826556e-01 5.93852264e-01]]

 [[4.66949704e-01 4.95765046e-01 5.49926629e-01]
  [1.71271989e-01 2.34652998e-02 4.88020991e-01]
  [2.39196055e-01 3.43176381e-01 2.25935470e-01]]

 [[1.55278343e-01 8.06067435e-01 5.94846728e-01]
  [1.67791990e-01 5.33879459e-02 5.89254084e-01]
  [1.16122398e-01 8.85256213e-01 4.37374920e-01]]]

10x10 array of random values from the uniform distribution
[[0.73584906 0.3265488

#### Task 7: Write code that uses the below matrix to reproduce the expected output

In [8]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)

In [9]:
mat_modified1 = mat[(mat > 11) & (mat != 16) & (mat != 21)].reshape(3, 4)

In [10]:
mat_modified1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [11]:
result = mat[3,4]

In [12]:
result

np.int64(20)

In [13]:
mat_modified2 = mat[(mat == 2) | (mat == 7) | (mat == 12)].reshape(3, 1)

In [14]:
mat_modified2

array([[ 2],
       [ 7],
       [12]])

In [15]:
mat_modified3 = mat[mat > 20]

In [16]:
mat_modified3

array([21, 22, 23, 24, 25])

In [17]:
mat_modified4 = mat[mat > 15].reshape(2, 5)

In [18]:
mat_modified4

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Task 8: Continue using the matrix `mat` to calculate the:

- sum of its values;
- standard deviation of its values;
- the sum of all the columns;

In [19]:
sum_of_mat = np.sum(mat)

In [20]:
sum_of_mat

np.int64(325)

In [21]:
std_of_mat = np.std(mat)

In [22]:
std_of_mat

np.float64(7.211102550927978)

In [ ]:
mat_values = np.sum(mat, axis=0)

In [32]:
mat_values

array([55, 60, 65, 70, 75])

#### Task 9: Let's practice composing operations:

1. Create a 1D array of random integers between $0$ and $9$. Negate all numbers that fall in the interval $[3, 8]$.
2. Create a random array with floating point values of size $10$ and sort it.
3. Create random vector of values drawn from the uniform distribution of size $10$ and replace the maximum value with $0$.

In [25]:
array_1 = np.array([-x if (x >= 3) & (x <= 8) else x for x in np.random.randint(0, 10, 10)])

In [26]:
array_1

array([-8, -4, -8,  9, -8, -7, -7, -7,  9,  9], dtype=int32)

In [27]:
array_2 = np.sort(np.random.rand(10))

In [28]:
array_2

array([0.14575031, 0.44759326, 0.47747193, 0.66757663, 0.69023282,
       0.70092588, 0.71246203, 0.8514912 , 0.88343183, 0.89568974])

In [29]:
array_3 = np.random.rand(10)
array_3 = np.array([0 if x == np.max(array_3) else x for x in array_3])

In [30]:
array_3

array([0.80410773, 0.92548625, 0.81182892, 0.94683536, 0.48156213,
       0.76535084, 0.        , 0.60016765, 0.45884327, 0.93567927])

#### Task 10: Reproducibility

When training models, it's often important to generate the same random numbers every time the application is run, even if the machine changes. This ability helps us remove the possibility of creating the situation: *Well, it works on my machine...*.

Our code should work on all machines and produce the same results across different runs.

Go through the [documentation](https://numpy.org/doc/stable/reference/module_structure.html) and answer the below question.

How can we ensure that we always get the same random numbers (even if we switch machines)? Give two examples.

> **Your answer**: We can ensure that using the same seed for random generation. The modern approach is to use the Generator API. This way the seed is set as: numpy.random.default_rng(seed=None). The older (legacy) way is to use: numpy.random.seed(seed=None)